import { container } from "tsyringe";
import IDBContext from "../../infrastructure/interfaces/IDbContext";
import DBContext from "../../infrastructure/database/DBContext";
import IProvedorRepository from "../../core/interfaces/IProvedorRepository";
import ProvedorRepository from "../../infrastructure/repositories/provedor.repository";
import IProvedorServices from "../../application/interfaces/IProvedorServices";
import ProvedorServices from "../../application/services/ProvedorServices";
import ApiReceitanetServices from "../../infrastructure/apis/receitanet/ApiReceitanetServices";
import IApiReceitanetServices from "../../infrastructure/apis/receitanet/interface/IApiReceitanetServices";
import ReceitanetServices from "../../application/services/ReceitanetServices";
import IReceitanetServices from "../../application/interfaces/IReceitanetServicest";
import ITokenService from "../../application/interfaces/ITokenService";
import TokenService from "../../application/services/TokenService";
import IApiIxcSoftService from "../../infrastructure/apis/ixcsoft/interfaces/IApiIxcSoftService";
import ApiIxcSoftService from "../../infrastructure/apis/ixcsoft/ApiIxcSoftService";
import IIxcSoftServices from "../../application/interfaces/IIxcSoftServices";
import IxcSoftServices from "../../application/services/IxcSoftServices";
import IPainelServices from "../../application/interfaces/IPainelService";
import PainelService from "../../application/services/PainelServices";
import PainelRepository from "../../infrastructure/repositories/painel.repository";
import IPainelRepository from "../../core/interfaces/IPainelRepository";
import IPushNotificationRepository from "../../core/interfaces/IPushNotificationRepository";
import PushNotificationRepository from "../../infrastructure/repositories/PushNotificationRepository";
import IPushNotificationServices from "../../application/interfaces/IPushNotificationServices";
import PushNotificationServices from "../../application/services/PushNotificationServices";
import IParceiroRepository from "../../core/interfaces/IParceiroRepository";
import ParceiroRepository from "../../infrastructure/repositories/parceiro.repository";
import IParceiroServices from "../../application/interfaces/IParceiroServices";
import ParceiroServices from "../../application/services/ParceiroServices";
import INotificacaoFaturaRepository from "../../core/interfaces/INotificacaoFaturaRepository";
import NotificacaoFaturaRepository from "../../infrastructure/repositories/NotificacaoFaturaRepository";
import INotificacaoFaturaServices from "../../application/interfaces/INotificacaoFaturaServices";
import NotificacaoFaturaServices from "../../application/services/NotificacaoFaturaServices";
import INotificacaoClienteRepository from "../../core/interfaces/INotificacaoClienteRepository";
import NotificacaoClienteRepository from "../../infrastructure/repositories/NotificacaoClienteRepository";
import INotificacaoTemplateRepository from "../../core/interfaces/INotificacaoTemplateRepository";
import NotificacaoTemplateRepository from "../../infrastructure/repositories/NotificacaoTemplateRepository";


container.registerSingleton<IDBContext>("IDBContext", DBContext);
container.registerSingleton<ITokenService>("ITokenService", TokenService);
container.registerSingleton<IIxcSoftServices>("IIxcSoftServices", IxcSoftServices);
container.registerSingleton<IReceitanetServices>("IReceitanetServices", ReceitanetServices);
container.registerSingleton<IApiReceitanetServices>("IApiReceitanetServices", ApiReceitanetServices);
container.registerSingleton<IApiIxcSoftService>("IApiIxcSoftService", ApiIxcSoftService);
container.registerSingleton<IProvedorRepository>("IProvedorRepository", ProvedorRepository);
container.registerSingleton<IProvedorServices>("IProvedorServices", ProvedorServices);
container.registerSingleton<IPainelServices>("IPainelServices", PainelService);
container.registerSingleton<IPainelRepository>("IPainelRepository", PainelRepository);
container.registerSingleton<IPushNotificationRepository>("IPushNotificationRepository", PushNotificationRepository);
container.registerSingleton<IPushNotificationServices>("IPushNotificationServices", PushNotificationServices);
container.registerSingleton<IParceiroRepository>("IParceiroRepository", ParceiroRepository);
container.registerSingleton<IParceiroServices>("IParceiroServices", ParceiroServices);
container.registerSingleton<INotificacaoFaturaRepository>("INotificacaoFaturaRepository", NotificacaoFaturaRepository);
container.registerSingleton<INotificacaoFaturaServices>("INotificacaoFaturaServices", NotificacaoFaturaServices);
container.registerSingleton<INotificacaoClienteRepository>("INotificacaoClienteRepository", NotificacaoClienteRepository);
container.registerSingleton<INotificacaoTemplateRepository>("INotificacaoTemplateRepository", NotificacaoTemplateRepository);
